/* standard choice disabled:  CTRCA:Planning/Subdivision/Subdivision/Combo

if (publicUser) {
	email('AustinAJ@elpasotexas.gov;MartinezAR@elpasotexas.gov;OrtizNX@elpasotexas.gov','accela@elpasotexas.gov','A new Combination Subdivision Application has been submitted online, application number is ' + capIDString + '.','A new Combination Subdivision Application has been submitted online, application number is ' + capIDString + '.');
	}

*/
